# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    prod:
      envName: "prod"
    homolog:
      envName: "homolog"
  maxParallel: 2

pool:
  name: linux
  demands: npm

steps:
- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build-$(envName)
  displayName: 'npm build'

- bash: |
   find dist/$(envName) -type f -exec sh -c "gzip < {} > {}.gz" \;
   find dist/$(envName) -type f -not -name "*.gz" -exec sh -c "brotli {}" \;
  displayName: 'Compress build files'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: dist
    ArtifactName: dist