# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master

strategy:
  matrix:
    prod:
      envName: "prod"
    homolog:
      envName: "homolog"
  maxParallel: 2

pool:
  name: linux
  demands: npm

steps:
- script: |
    npm install --prefix src/events
  displayName: 'npm install'

- script: |
    npm rebuild node-sass
  displayName: 'npm rebuild node-sass'

- script: |
    npm rebuild node-sass
    npm run build --prefix src/events
  displayName: 'npm build'

- bash: |
   find dist/v2/$(envName) -type f -exec sh -c "gzip < {} > {}.gz" \;
   find dist/v2/$(envName) -type f -not -name "*.gz" -exec sh -c "brotli {}" \;
  displayName: 'Compress build files'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: dist
    ArtifactName: dist