# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master


strategy:
  matrix:
    prod:
      envName: "prod"
  maxParallel: 2


pool:
  name: linux
  demands: npm

steps:
# - task: npmAuthenticate@0
#   displayName: 'npm authenticate'
#   inputs:
#     workingFile: src/events/.npmrc
#     customEndpoint: 'vsts-npm-auth'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  enabled: false

- script: |
    npm install --prefix src/events
  displayName: 'npm install'

- task: Bash@3
  displayName: 'versioning via gitversion.sh'
  inputs:
    targetType: filePath
    filePath: ./gitversion.sh
  enabled: false

- script: |
    npm run build --prefix src/events
  displayName: 'npm build'

- bash: |
    find src/events/dist -type f -exec sh -c "gzip < {} > {}.gz" \;
    find src/events/dist -type f -not -name "*.gz" -exec sh -c "brotli {}" \;
  displayName: 'Compress build files'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: src/events/dist
    ArtifactName: dist